---
title: "Q1: Linear Regresson"
output: html_notebook
---

```{r}
rm(list = ls())
datf <- readRDS("~/GitHub/MatrixTSA/soenderborg_2day.RDS")
```

# Linear Regression of Data in Winter Period

## Set the summer period values to NA

```{r}
## Find the day of year for starting and ending summer
as.POSIXlt("2011-06-01")$yday
as.POSIXlt("2011-10-01")$yday
## Find index of summer and set measurements to NA
isummer <- 151 < as.POSIXlt(df_x$t)$yday & as.POSIXlt(df_x$t)$yday <= 273
df_x[isummer, -1] <- NA
```

## Simplest linear model

```{r}
fit_winter <- lm(P ~ Te, df_x)
summary(fit_winter)
plot(df_x$Te, df_x$P)  # relation between external temperature and heat load
abline(fit_winter)
```

## Model validation of Regression Model

```{r}
par(mfrow = c(2, 2))
## Plot residuals
plot(fit_winter$residuals)
## Residulas vs. input Te
plot(df_x$Te[as.integer(names(fit_winter$residuals))], fit_winter$residuals)
hist(fit_winter$residuals)
qqnorm(fit_winter$residuals)
qqline(fit_winter$residuals)
```

```{r}
par(mfrow = c(1,1))
acf(fit_winter$residuals)
```

