---
title: "State Space Model of a Falling Body"
output: html_notebook
author: Lasse Engbo Christiansen
---

```{r}
## Simulating a falling body:
## We start at 10000 m and drop the body.
z_0 <- 10000
matA <- matrix(c(1,0,1,1), nrow = 2)
matB <- matrix(c(-.5,-1),nrow=2)
matC <- matrix(c(1,0),nrow=1)
matSigma_1 <- 100*matrix(c(2,.8,.8,1),nrow=2)
matSigma_2 <- matrix(10000)

g <- 9.82 ## m/s2
N <- 100
matX <- matrix(nrow = 2, ncol = N)
matX[,1] <- c(z_0, 0)
vecY <- numeric(N)
vecY[1] <- matC %*% matX[,1] + sqrt(matSigma_2) %*% rnorm(1)
## Simulation
for (i in 2:N){
    matX[,i] <- matA %*% matX[, i - 1, drop = FALSE] + matB %*% g + chol(matSigma_1) %*% matrix(rnorm(2), ncol = 1)
    vecY[i] <- matC %*% matX[,i] + sqrt(matSigma_2) %*% rnorm(1)
}
# Cut off the data when hit the ground
Nhit <- min(which(matX[1,] < 0)) - 1
matX <- matX[, 1:Nhit]
vecY <- vecY[1:Nhit]

## Plotting our observations
plot(matX[1,])
plot(matX[2,])
plot(vecY)
```

```{r}
library("FKF")
## Running the Kalman filter with the parameters and initial values used for the simulation
kf1 <- fkf(a0 = c(10000,0), P0 = diag(0,2),dt = matB %*% g, Tt = matA, ct = 0, Zt = matC, HHt = matSigma_1, 
           GGt = matSigma_2, yt = matrix(vecY,nrow=1))
str(kf1)

plot(kf1$at[1,])
plot(kf1$at[2,])
plot(sqrt(kf1$Pt[1,1,]))
plot(sqrt(kf1$Pt[2,2,]))
plot(sqrt(kf1$Ptt[1,1,]))


plot(vecY)
kf1$logLik
with(kf1, matlines((at[1,]) + cbind(0, -1.96 * sqrt(Pt[1,1,]), 1.96 * sqrt(Pt[1,1,])), type="l", lty=c(1,2,2), col=2))

## Running the Kalman filter with wrong initial height
kf1w0 <- fkf(a0=c(6000,0), P0 = diag(0,2),dt = matB%*%g, Tt = matA, ct=0, Zt = matC, HHt = matSigma_1, GGt = matSigma_2, yt = matrix(vecY,nrow=1))
kf1w0$logLik
with(kf1w0, matlines((at[1,]) + cbind(0,-1.96*sqrt(Pt[1,1,]),1.96*sqrt(Pt[1,1,])),type="l", lty=c(1,2,2), col=3))

## Running the Kalman filter with wrong initial height and increased initial uncertainty
kf1vl <- fkf(a0=c(6000,0), P0 = diag(100000,2),dt = matB%*%g, Tt = matA, ct=0, Zt = matC, HHt = matSigma_1, GGt = matSigma_2, yt = matrix(vecY,nrow=1))
kf1vl$logLik
with(kf1vl, matlines((at[1,]) + cbind(0,-1.96*sqrt(Pt[1,1,]),1.96*sqrt(Pt[1,1,])),type="l", lty=c(1,2,2), col=4))

## Plotting the filtered velocities
with(kf1, matplot((at[2,]) + cbind(0,-1.96*sqrt(Pt[2,2,]),1.96*sqrt(Pt[2,2,])),type="l", lty=c(1,2,2), col=2))

## What if some observations were missing:
length(vecY)
Ymis <- vecY
Ymis[sample(Nhit,36)] <- NA
plot(Ymis, ylim=c(0,12000))

kf1mis <- fkf(a0=c(10000,0), P0 = diag(0,2),dt = matB%*%g, Tt = matA, ct=0, Zt = matC, HHt = matSigma_1*100, GGt = matSigma_2, yt = matrix(Ymis,nrow=1))
with(kf1mis, matlines((at[1,]) + cbind(0,-1.96*sqrt(Pt[1,1,]),1.96*sqrt(Pt[1,1,])),type="l", lty=c(1,2,2), col=3, lwd=2))


```

